FROM openjdk:17-jdk-slim
WORKDIR /Users/zhou/Documents/java/ideaProjects/SpringCloudLearning/SpringCloud/product/target
COPY product-1.0-SNAPSHOT.jar .
EXPOSE 8080
CMD ["java", "-jar", "product-1.0-SNAPSHOT.jar"]