FROM openjdk:17-jdk-slim
WORKDIR /Users/zhou/Documents/java/ideaProjects/SpringCloudLearning/SpringCloud/uaa/target
COPY uaa-1.0-SNAPSHOT.jar .
EXPOSE 8080
CMD ["java", "-jar", "uaa-1.0-SNAPSHOT.jar"]